#!/usr/bin/env python3
"""Simulate following CreamCream1215 weather trades.

This is read-only and never places orders. It watches the local
creamcream_activity.csv generated by watch_creamcream_activity.py and creates a
small simulated follow trade for selected BUY activity.
"""

from __future__ import annotations

import argparse
import csv
import re
import time
import urllib.parse
import urllib.request
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from trade_audit import ensure_audit_open, order_snapshot, signal_time_from_epoch, update_audit_marks


@dataclass
class CopyTrade:
    id: str
    ts: str
    source_seen_at: str
    action: str
    outcome: str
    source_price: float
    sim_entry_price: float
    stake: float
    shares: float
    title: str
    slug: str
    event_slug: str
    status: str
    result: str = ""
    pnl: float = 0.0


def fnum(value: Any) -> float:
    try:
        return float(value)
    except Exception:
        return 0.0


def http_json(url: str) -> Any:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0", "Connection": "close"})
    with urllib.request.urlopen(req, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def event_markets(event_slug: str) -> list[dict[str, Any]]:
    query = urllib.parse.urlencode({"slug": event_slug})
    data = http_json(f"https://gamma-api.polymarket.com/events?{query}")
    if isinstance(data, list) and data:
        return data[0].get("markets") or []
    return []


def market_by_slug(slug: str) -> dict[str, Any] | None:
    query = urllib.parse.urlencode({"slug": slug})
    data = http_json(f"https://gamma-api.polymarket.com/markets?{query}")
    if isinstance(data, list) and data:
        return data[0]
    data = http_json(f"https://gamma-api.polymarket.com/events?{query}")
    if isinstance(data, list) and data:
        markets = data[0].get("markets") or []
        if markets:
            return markets[0]
    return None


def latest_market_price(slug: str, outcome: str) -> float | None:
    market = market_by_slug(slug)
    if not market:
        return None
    outcomes = json.loads(market.get("outcomes") or "[]")
    prices = json.loads(market.get("outcomePrices") or "[]")
    for name, price in zip(outcomes, prices):
        if str(name).lower() == outcome.lower():
            return float(price)
    return None


def resolve_temperature_from_title(title: str) -> int | None:
    match = re.search(r"(\d+)\s*°?C", title)
    return int(match.group(1)) if match else None


def read_source_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def read_copy_rows(path: Path) -> dict[str, dict[str, str]]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as file:
        rows = {}
        for row in csv.DictReader(file):
            rows[row["id"]] = row
        return rows


def append_row(path: Path, row: dict[str, Any]) -> None:
    fields = [
        "ts",
        "id",
        "source_seen_at",
        "action",
        "outcome",
        "source_price",
        "sim_entry_price",
        "stake",
        "shares",
        "title",
        "slug",
        "event_slug",
        "status",
        "result",
        "current_price",
        "pnl",
    ]
    exists = path.exists()
    with path.open("a", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fields)
        if not exists:
            writer.writeheader()
        writer.writerow({field: row.get(field, "") for field in fields})


def source_id(row: dict[str, str]) -> str:
    return f"{row.get('tx')}:{row.get('slug')}:{row.get('side')}:{row.get('outcome')}:{row.get('usdcSize')}"


def should_copy(row: dict[str, str], args: argparse.Namespace) -> bool:
    if row.get("side") != "BUY":
        return False
    if row.get("outcome") != "Yes":
        return False
    title = row.get("title") or ""
    if "Hong Kong" not in title or "highest temperature" not in title:
        return False
    price = fnum(row.get("price"))
    usdc = fnum(row.get("usdcSize"))
    temp = resolve_temperature_from_title(title)
    if temp is None:
        return False
    if temp < args.min_temp or temp > args.max_temp:
        return False
    if price < args.min_price or price > args.max_price:
        return False
    signal_age = time.time() - fnum(row.get("timestamp"))
    if signal_age < 0 or signal_age > args.max_source_age_sec:
        return False
    return usdc >= args.min_source_usdc


def source_group_stats(rows: list[dict[str, str]], event_slug: str) -> dict[str, dict[str, float]]:
    stats: dict[str, dict[str, float]] = {}
    for row in rows:
        if row.get("eventSlug") != event_slug:
            continue
        slug = row.get("slug") or ""
        if not slug:
            continue
        entry = stats.setdefault(slug, {"buy_count": 0.0, "buy_usdc": 0.0, "sell_usdc": 0.0, "last_ts": 0.0})
        if row.get("side") == "BUY" and row.get("outcome") == "Yes":
            entry["buy_count"] += 1
            entry["buy_usdc"] += fnum(row.get("usdcSize"))
            entry["last_ts"] = max(entry["last_ts"], fnum(row.get("timestamp")))
        elif row.get("side") == "SELL":
            entry["sell_usdc"] += fnum(row.get("usdcSize"))
    return stats


def should_copy_with_context(row: dict[str, str], source_rows: list[dict[str, str]], args: argparse.Namespace) -> bool:
    if not should_copy(row, args):
        return False
    event_slug = row.get("eventSlug") or ""
    slug = row.get("slug") or ""
    stats = source_group_stats(source_rows, event_slug)
    current = stats.get(slug)
    if not current:
        return False
    if current["buy_count"] < args.min_cluster_buys:
        return False
    if current["buy_usdc"] < args.min_cluster_usdc:
        return False
    if current["sell_usdc"] > current["buy_usdc"] * args.max_sell_ratio:
        return False

    ranked = sorted(stats.items(), key=lambda item: (item[1]["last_ts"], item[1]["buy_usdc"]), reverse=True)
    leaders = {item[0] for item in ranked[: args.cluster_rank_limit]}
    return slug in leaders


def market_exposure(log_path: Path, slug: str) -> tuple[float, int]:
    rows = read_copy_rows(log_path)
    stake = 0.0
    count = 0
    for row in rows.values():
        if row.get("slug") != slug:
            continue
        if row.get("status") not in {"OPEN", "MARK"}:
            continue
        stake += fnum(row.get("stake"))
        count += 1
    return stake, count


def create_copy(row: dict[str, str], args: argparse.Namespace) -> None:
    price = fnum(row.get("price"))
    slug = row.get("slug") or ""
    outcome = row.get("outcome") or "Yes"
    market_stake, market_count = market_exposure(args.log, slug)
    if market_stake >= args.max_market_stake_usdc:
        print(f"跳过CreamCream信号：单市场模拟暴露已满 {market_stake:.2f}U | {row.get('title')}", flush=True)
        return
    if market_count >= args.max_market_entries:
        print(f"跳过CreamCream信号：单市场重复过多 {market_count}次 | {row.get('title')}", flush=True)
        return
    stake = min(args.stake_usdc, args.bankroll_usdc, max(0.0, args.max_market_stake_usdc - market_stake))
    if stake <= 0:
        return
    trade_id = source_id(row)
    market = market_by_slug(slug)
    try:
        snapshot = order_snapshot(market, outcome, stake) if market else {}
    except Exception:
        snapshot = {}
    entry = fnum(snapshot.get("sim_fill_price")) or price
    best_ask = fnum(snapshot.get("best_ask"))
    ask_depth_usdc = fnum(snapshot.get("ask_depth_usdc"))
    would_live_fill = bool(snapshot.get("would_live_fill"))
    slippage_bps = ((entry - price) / price * 10000) if price > 0 else 0.0
    source_to_ask_gap = best_ask - price if best_ask > 0 and price > 0 else 999.0
    if args.require_live_fill and not would_live_fill:
        print(f"跳过CreamCream信号：盘口深度不足 | {row.get('title')}", flush=True)
        return
    if ask_depth_usdc < args.min_ask_depth_usdc:
        print(f"跳过CreamCream信号：ask深度不足 {ask_depth_usdc:.2f}U | {row.get('title')}", flush=True)
        return
    if slippage_bps > args.max_slippage_bps:
        print(f"跳过CreamCream信号：滑点过高 {slippage_bps:.0f}bps | {row.get('title')}", flush=True)
        return
    if source_to_ask_gap > args.max_source_to_ask_gap:
        print(f"跳过CreamCream信号：源价到ask差距 {source_to_ask_gap:.3f} | {row.get('title')}", flush=True)
        return
    shares = fnum(snapshot.get("sim_shares")) or (stake / entry if entry > 0 else 0.0)
    ensure_audit_open(
        args.audit_log,
        trade_id=trade_id,
        strategy="creamcream_copy",
        wallet_name="CreamCream1215",
        signal_time=signal_time_from_epoch(row.get("timestamp")),
        title=row.get("title") or "",
        slug=slug,
        event_slug=row.get("eventSlug") or "",
        outcome=outcome,
        stake=stake,
        source_price=price,
        market=market,
    )
    append_row(
        args.log,
        {
            "ts": datetime.now(timezone.utc).isoformat(),
            "id": trade_id,
            "source_seen_at": row.get("seen_at"),
            "action": "COPY_BUY",
            "outcome": outcome,
            "source_price": f"{price:.6f}",
            "sim_entry_price": f"{entry:.6f}",
            "stake": f"{stake:.4f}",
            "shares": f"{shares:.4f}",
            "title": row.get("title"),
            "slug": slug,
            "event_slug": row.get("eventSlug"),
            "status": "OPEN",
        },
    )
    alert = (
        f"CREAMCREAM COPY SIM\n"
        f"time: {datetime.now(timezone.utc).isoformat()}\n"
        f"stake: {stake:.2f}U\n"
        f"entry_price: {entry:.4f}\n"
        f"source_price: {price:.4f}\n"
        f"slippage_bps: {slippage_bps:.0f}\n"
        f"ask_depth_usdc: {ask_depth_usdc:.2f}U\n"
        f"shares: {shares:.4f}\n"
        f"market: {row.get('title')}\n"
        f"url: https://polymarket.com/event/{row.get('eventSlug')}\n"
    )
    args.alert_file.write_text(alert, encoding="utf-8")
    print(f"CreamCream天气跟单模拟开仓：{stake:.2f}U @ {entry:.3f} | {row.get('title')}", flush=True)


def update_open_rows(args: argparse.Namespace) -> None:
    rows = read_copy_rows(args.log)
    for row in rows.values():
        if row.get("status") != "OPEN":
            continue
        current = latest_market_price(row["slug"], row.get("outcome") or "Yes")
        if current is None:
            continue
        shares = fnum(row.get("shares"))
        stake = fnum(row.get("stake"))
        mark_pnl = shares * current - stake
        append_row(
            args.log,
            {
                **row,
                "ts": datetime.now(timezone.utc).isoformat(),
                "status": "MARK",
                "result": "MARK",
                "current_price": f"{current:.6f}",
                "pnl": f"{mark_pnl:.4f}",
            },
        )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=Path("creamcream_activity.csv"))
    parser.add_argument("--log", type=Path, default=Path("creamcream_copy_sim.csv"))
    parser.add_argument("--audit-log", type=Path, default=Path("creamcream_trade_audit.csv"))
    parser.add_argument("--alert-file", type=Path, default=Path("latest_creamcream_copy_alert.txt"))
    parser.add_argument("--interval", type=float, default=30.0)
    parser.add_argument("--stake-usdc", type=float, default=5.0)
    parser.add_argument("--bankroll-usdc", type=float, default=1000.0)
    parser.add_argument("--min-source-usdc", type=float, default=3.0)
    parser.add_argument("--min-price", type=float, default=0.05)
    parser.add_argument("--max-price", type=float, default=0.75)
    parser.add_argument("--min-temp", type=int, default=27)
    parser.add_argument("--max-temp", type=int, default=32)
    parser.add_argument("--min-cluster-buys", type=int, default=3)
    parser.add_argument("--min-cluster-usdc", type=float, default=25.0)
    parser.add_argument("--cluster-rank-limit", type=int, default=2)
    parser.add_argument("--max-sell-ratio", type=float, default=0.35)
    parser.add_argument("--max-source-age-sec", type=float, default=15.0)
    parser.add_argument("--max-slippage-bps", type=float, default=250.0)
    parser.add_argument("--max-source-to-ask-gap", type=float, default=0.02)
    parser.add_argument("--min-ask-depth-usdc", type=float, default=20.0)
    parser.add_argument("--max-market-stake-usdc", type=float, default=10.0)
    parser.add_argument("--max-market-entries", type=int, default=2)
    parser.add_argument("--require-live-fill", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--max-audit-updates", type=int, default=50)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    while True:
        try:
            copied = read_copy_rows(args.log)
            source_rows = read_source_rows(args.source)
            opened = 0
            for row in source_rows:
                sid = source_id(row)
                if sid in copied:
                    continue
                if should_copy_with_context(row, source_rows, args):
                    create_copy(row, args)
                    copied[sid] = row
                    opened += 1
            update_open_rows(args)
            update_audit_marks(args.audit_log, market_by_slug, max_rows=args.max_audit_updates)
            print(
                f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] 天气跟单模拟扫描 | 新开仓 {opened} 条",
                flush=True,
            )
        except KeyboardInterrupt:
            return 130
        except Exception as exc:
            print(f"天气跟单模拟错误：{exc}", flush=True)
        time.sleep(args.interval)


if __name__ == "__main__":
    raise SystemExit(main())
